### ISSUE TITLE
Error Fakeinventories 1.0.3

### ISSUE THREAD

**Issue by PocketMiner92** [CloudburstMC/FakeInventories#8]
1;31mERROR[m[m] Das Event "cn.nukkit.event.server.DataPacketSendEvent" konnte nicht zu "FakeInventories v1.0.3": null in Zeile com.nukkitx.fakeinventories.FakeInventoriesListener weitergegeben werden

cn.nukkit.utils.EventException: null

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:35) ~[nukkit-stable.jar:?]

at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:60) ~[nukkit-stable.jar:?]

at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:572) [nukkit-stable.jar:?]

at cn.nukkit.Player.dataPacket(Player.java:1167) [nukkit-stable.jar:?]

at Crafting.API.CraftingTable.placeChest(CraftingTable.java:70) [Crafting.jar:?]

at Crafting.API.CraftingTable.onOpenBlock(CraftingTable.java:57) [Crafting.jar:?]

at Crafting.API.FakeCraftingTable.onOpen(FakeCraftingTable.java:62) [Crafting.jar:?]

at cn.nukkit.inventory.BaseInventory.open(BaseInventory.java:433) [nukkit-stable.jar:?]

at cn.nukkit.Player.addWindow(Player.java:5473) [nukkit-stable.jar:?]

at cn.nukkit.Player.addWindow(Player.java:5453) [nukkit-stable.jar:?]

at cn.nukkit.Player.addWindow(Player.java:5449) [nukkit-stable.jar:?]

at cn.nukkit.Player.addWindow(Player.java:5445) [nukkit-stable.jar:?]

at Crafting.commands.Craft.execute(Craft.java:22) [Crafting.jar:?]

at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:259) [nukkit-stable.jar:?]

at cn.nukkit.Server.dispatchCommand(Server.java:964) [nukkit-stable.jar:?]

at cn.nukkit.Player.handleDataPacket(Player.java:3203) [nukkit-stable.jar:?]

at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:129) [nukkit-stable.jar:?]

at cn.nukkit.network.Network.processInterfaces(Network.java:170) [nukkit-stable.jar:?]

at cn.nukkit.Server.tick(Server.java:1363) [nukkit-stable.jar:?]

at cn.nukkit.Server.tickProcessor(Server.java:1146) [nukkit-stable.jar:?]

at cn.nukkit.Server.start(Server.java:1106) [nukkit-stable.jar:?]

at cn.nukkit.Server.<init>(Server.java:778) [nukkit-stable.jar:?]

at cn.nukkit.Nukkit.main(Nukkit.java:200) [nukkit-stable.jar:?]

Caused by: java.lang.IllegalAccessError: tried to access field com.nukkitx.fakeinventories.inventory.FakeInventory.open from class com.nukkitx.fakeinventories.inventory.FakeInventories

at com.nukkitx.fakeinventories.inventory.FakeInventories.getFakeInventoryPositions(FakeInventories.java:11) ~[?:?]

at com.nukkitx.fakeinventories.FakeInventoriesListener.onPacketSend(FakeInventoriesListener.java:32) ~[?:?]

at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:30) ~[nukkit-stable.jar:?]

I use Craft Plugin

**Comment by PocketMiner92** [comment]
@SupremeMortal Any News?
